[package]
name = "server"
version = "0.1.0"
authors = ["0zark <siddhant@hey.com>"]
edition = "2018"

[dependencies]

tide = "0.13.0"
async-std = { version = "1.6.3", features = ["attributes"] }
flate2 = { version = "1.0", features = ["zlib"], default-features = false }
percent-encoding = "2.1.0"
askama = "0.10.3"
anyhow = "1.0.32"
dotenv = "0.15.0"
lazy_static = "1.4.0"